-- phpMyAdmin SQL Dump
-- version 4.9.5
-- https://www.phpmyadmin.net/
--
-- Host: localhost:8889
-- Generation Time: Mar 18, 2021 at 10:16 AM
-- Server version: 5.7.30
-- PHP Version: 7.3.21

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `shop`
--

-- --------------------------------------------------------

--
-- Table structure for table `cart`
--

CREATE TABLE `cart` (
  `ID` int(11) NOT NULL,
  `model_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `quantity` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `car_brand`
--

CREATE TABLE `car_brand` (
  `brand_id` int(11) NOT NULL,
  `brand` varchar(63) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `car_brand`
--

INSERT INTO `car_brand` (`brand_id`, `brand`) VALUES
(1, 'Audi'),
(2, 'BMW'),
(3, 'Mercedes-Benz'),
(4, 'Lexus'),
(5, 'Toyota'),
(6, 'Land Rover'),
(7, 'KIA'),
(8, 'Nissan'),
(9, 'Honda'),
(10, 'Hyundai');

-- --------------------------------------------------------

--
-- Table structure for table `models`
--

CREATE TABLE `models` (
  `model_id` int(11) NOT NULL,
  `brand_id` int(11) NOT NULL,
  `model` varchar(100) NOT NULL,
  `price` double NOT NULL,
  `info_brief` text NOT NULL,
  `info_full` text NOT NULL,
  `photo_path` varchar(64) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `models`
--

INSERT INTO `models` (`model_id`, `brand_id`, `model`, `price`, `info_brief`, `info_full`, `photo_path`) VALUES
(1, 1, 'A3 Sedan', 2300000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'AudiA3Sedan'),
(5, 1, 'A4 Avant', 2900000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'AudiA4Avant'),
(6, 1, 'A5 Coupe', 3300000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'AudiA5Coupe'),
(7, 1, 'A6 Avant', 4200000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'AudiA6Avant'),
(8, 1, 'A7 Sportback', 4700000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'AudiA7Sportback'),
(9, 1, 'A8 L', 7800000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'AudiA8L'),
(10, 1, 'Q3', 3100000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'AudiQ3'),
(11, 1, 'Q5', 4150000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'AudiQ5'),
(12, 1, 'Q7', 5700000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'AudiQ7'),
(13, 1, 'Q8', 6100000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'AudiQ8'),
(14, 1, 'RS6 Avant', 10800000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'AudiRS6Avant'),
(15, 1, 'S6', 6700000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'AudiS6'),
(16, 1, 'S8', 12200000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'AudiS8'),
(17, 1, 'SQ8', 7800000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'AudiSQ8'),
(18, 2, '4 Series', 35000000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'BMW4Series'),
(19, 2, '5 Series', 43000000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'BMW5Series'),
(20, 2, '6 Series GT', 5250000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'BMW6SeriesGT'),
(21, 2, '7 Series', 7150000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'BMW7Series'),
(22, 2, '8 Series Coupe', 8100000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'BMW8SeriesCoupe'),
(23, 2, '8 Series Gran Coupe', 7700000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'BMW8SeriesGranCoupe'),
(24, 2, 'i8 Coupe', 11000000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'BMWi8Coupe'),
(25, 2, 'M2 Coupe', 6900000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'BMWM2Coupe'),
(26, 2, 'M4 Coupe', 7600000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'BMWM4Coupe'),
(27, 2, 'M5 ', 9300000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'BMWM5'),
(28, 2, 'M8 Coupe', 12400000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'BMWM8Coupe'),
(29, 2, 'X5', 5550000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'BMWX5'),
(30, 2, 'X5M', 10200000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'BMWX5M'),
(31, 2, 'X6', 6200000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'BMWX6'),
(32, 2, 'X6M', 11150000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'BMWX6M'),
(33, 2, 'X7', 7600000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'BMWX7'),
(34, 3, 'A-Klasse', 2560000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'MercA'),
(35, 3, 'AMG GT', 8380000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'MercAMGGT'),
(36, 3, 'C-Klasse', 2920000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'MercC'),
(37, 3, 'CLA-Klasse', 2850000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'MercCLA'),
(38, 3, 'CLS-Klasse', 6090000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'MercCLS'),
(39, 3, 'E-Klasse', 4020000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'MercE'),
(40, 3, 'G-Klasse', 11280000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'MercG'),
(41, 3, 'GLA-Klasse', 3830000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'MercGLA'),
(42, 3, 'GLB-Klasse', 2970000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'MercGLB'),
(43, 3, 'GLC-Klasse', 4490000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'MercGLC'),
(44, 3, 'GLE-Klasse', 5860000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'MercGLE'),
(45, 3, 'GLS-Klasse', 8980000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'MercGLS'),
(46, 3, 'S-Klasse', 11270000, 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'MercS');
INSERT INTO `models` (`model_id`, `brand_id`, `model`, `price`, `info_brief`, `info_full`, `photo_path`) VALUES
(56, 4, 'GX 460', 5180000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'LexusGX460'),
(57, 4, 'LC 500', 8870000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'LexusLC500'),
(58, 4, 'LS 500', 8990000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'LexusLS500'),
(59, 4, 'LX 570', 7060000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'LexusLX570'),
(60, 4, 'NX 300', 3369000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'LexusNX300'),
(61, 4, 'RX 350', 4625000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'LexusRX350'),
(62, 4, 'UX 200', 2612000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'LexusUX200'),
(63, 4, 'ES 350', 3203000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'LexusES350'),
(64, 5, 'Supra', 5534000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'ToyotaSupra'),
(65, 5, 'Land Cruiser 200', 5238000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'ToyotaLC200'),
(66, 5, 'Hilux', 2610000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'ToyotaHilux'),
(67, 5, 'Alphard', 5455000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'ToyotaAlphard'),
(68, 5, 'Highlander', 3813000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'ToyotaHighlander'),
(69, 5, 'Camry', 1779000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Mauris a diam maecenas sed enim ut sem viverra. Nam at lectus urna duis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Gravida arcu ac tortor dignissim convallis aenean et. Egestas diam in arcu cursus euismod quis viverra nibh cras. Diam maecenas sed enim ut sem. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.', 'ToyotaCamry');

-- --------------------------------------------------------

--
-- Table structure for table `orders`
--

CREATE TABLE `orders` (
  `order_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `address` text NOT NULL,
  `date-time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `amount` double NOT NULL,
  `order_status_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `orders`
--

INSERT INTO `orders` (`order_id`, `user_id`, `address`, `date-time`, `amount`, `order_status_id`) VALUES
(1, 1, '1231sdcwefcwcwsdcsdc', '2021-03-16 13:18:01', 2300000, 3),
(2, 1, 'evexceved', '2021-03-16 13:26:48', 2300000, 1),
(4, 1, 'wefiwvi iiv', '2021-03-16 13:34:59', 14750000, 4);

-- --------------------------------------------------------

--
-- Table structure for table `order_items`
--

CREATE TABLE `order_items` (
  `order_id` int(11) NOT NULL,
  `item_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `order_items`
--

INSERT INTO `order_items` (`order_id`, `item_id`) VALUES
(1, 1),
(2, 1),
(4, 33),
(4, 21);

-- --------------------------------------------------------

--
-- Table structure for table `order_status`
--

CREATE TABLE `order_status` (
  `order_status_id` int(11) NOT NULL,
  `status_name` varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `order_status`
--

INSERT INTO `order_status` (`order_status_id`, `status_name`) VALUES
(1, 'Создан'),
(2, 'В работе'),
(3, 'Передан в доставку'),
(4, 'Доставлен');

-- --------------------------------------------------------

--
-- Table structure for table `roles`
--

CREATE TABLE `roles` (
  `role_id` int(11) NOT NULL,
  `role` varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `roles`
--

INSERT INTO `roles` (`role_id`, `role`) VALUES
(1, 'customer'),
(2, 'admin');

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `user_id` int(11) NOT NULL,
  `mail` varchar(100) NOT NULL,
  `pass` varchar(100) NOT NULL,
  `role_id` int(11) NOT NULL DEFAULT '1'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`user_id`, `mail`, `pass`, `role_id`) VALUES
(1, 'brumbellow@mail.com', '123456789', 2),
(2, ':mail', ':pass', 1),
(3, 'ceh9.baybakov@gmail.com', '1sdcskmvselv', 1),
(5, 'regmail', 'regpass', 1),
(6, 'ars@sc.ru', 'wefwvcw', 1);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `cart`
--
ALTER TABLE `cart`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `user_id` (`user_id`),
  ADD KEY `model_id` (`model_id`);

--
-- Indexes for table `car_brand`
--
ALTER TABLE `car_brand`
  ADD PRIMARY KEY (`brand_id`);

--
-- Indexes for table `models`
--
ALTER TABLE `models`
  ADD PRIMARY KEY (`model_id`),
  ADD KEY `brand_id` (`brand_id`);

--
-- Indexes for table `orders`
--
ALTER TABLE `orders`
  ADD PRIMARY KEY (`order_id`),
  ADD KEY `user_id` (`user_id`),
  ADD KEY `order_status_id` (`order_status_id`);

--
-- Indexes for table `order_items`
--
ALTER TABLE `order_items`
  ADD KEY `order_id` (`order_id`),
  ADD KEY `item_id` (`item_id`);

--
-- Indexes for table `order_status`
--
ALTER TABLE `order_status`
  ADD PRIMARY KEY (`order_status_id`);

--
-- Indexes for table `roles`
--
ALTER TABLE `roles`
  ADD PRIMARY KEY (`role_id`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`user_id`),
  ADD KEY `role_id` (`role_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `cart`
--
ALTER TABLE `cart`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `car_brand`
--
ALTER TABLE `car_brand`
  MODIFY `brand_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

--
-- AUTO_INCREMENT for table `models`
--
ALTER TABLE `models`
  MODIFY `model_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=70;

--
-- AUTO_INCREMENT for table `orders`
--
ALTER TABLE `orders`
  MODIFY `order_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `order_status`
--
ALTER TABLE `order_status`
  MODIFY `order_status_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `roles`
--
ALTER TABLE `roles`
  MODIFY `role_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `user_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `cart`
--
ALTER TABLE `cart`
  ADD CONSTRAINT `cart_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`),
  ADD CONSTRAINT `cart_ibfk_2` FOREIGN KEY (`model_id`) REFERENCES `models` (`model_id`);

--
-- Constraints for table `models`
--
ALTER TABLE `models`
  ADD CONSTRAINT `models_ibfk_1` FOREIGN KEY (`brand_id`) REFERENCES `car_brand` (`brand_id`);

--
-- Constraints for table `orders`
--
ALTER TABLE `orders`
  ADD CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`),
  ADD CONSTRAINT `orders_ibfk_2` FOREIGN KEY (`order_status_id`) REFERENCES `order_status` (`order_status_id`);

--
-- Constraints for table `order_items`
--
ALTER TABLE `order_items`
  ADD CONSTRAINT `order_items_ibfk_1` FOREIGN KEY (`order_id`) REFERENCES `orders` (`order_id`),
  ADD CONSTRAINT `order_items_ibfk_2` FOREIGN KEY (`item_id`) REFERENCES `models` (`model_id`);

--
-- Constraints for table `user`
--
ALTER TABLE `user`
  ADD CONSTRAINT `user_ibfk_1` FOREIGN KEY (`role_id`) REFERENCES `roles` (`role_id`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
